services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r ./cab/requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn cab.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cab.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
